# Generated by Django 6.0.7 on 2026-07-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_candidate_election_vote_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_open_registeration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='election',
            name='is_opened_voting',
            field=models.BooleanField(default=False),
        ),
    ]
