# Generated by Django 6.0.7 on 2026-07-14 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_election_is_open_registeration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 14, 4, 37, 1, 827016, tzinfo=datetime.timezone.utc)),
        ),
    ]
