# Generated by Django 6.0.7 on 2026-07-16 20:38

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_election_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_photo',
            field=models.ImageField(default=None, null=True, upload_to='candidate_photos/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 16, 20, 38, 34, 296113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('election', 'user', 'position'), name='one_vote_per_position'),
        ),
    ]
