# Generated by Django 6.0.7 on 2026-07-17 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_candidate_candidate_photo_candidate_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_open_registeration',
        ),
        migrations.RemoveField(
            model_name='election',
            name='is_opened_voting',
        ),
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('VOTING', 'Voting'), ('CLOSED', 'Closed')], default='Voting', max_length=20),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 17, 2, 48, 59, 336311, tzinfo=datetime.timezone.utc)),
        ),
    ]
