# Generated by Django 6.0.7 on 2026-07-23 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_election_is_open_registeration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 3, 13, 51, 784425, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('VOTING', 'Voting'), ('CLOSED', 'Closed')], default='REGISTRATION', max_length=20),
        ),
    ]
