# Generated by Django 6.0.7 on 2026-07-24 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_election_end_date_alter_election_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 24, 19, 6, 20, 113152, tzinfo=datetime.timezone.utc)),
        ),
    ]
