# Generated by Django 6.0.7 on 2026-07-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_election_end_date_alter_student_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
